"""
PDF report generator — Penta Real Estate.
Produces a professional match report using ReportLab.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

# ── Brand colours ──────────────────────────────────────────────────────────
BLACK      = colors.HexColor("#000000")
WHITE      = colors.HexColor("#FFFFFF")
GOLD       = colors.HexColor("#C9A96E")
DARK_GREY  = colors.HexColor("#1A1A1A")
MID_GREY   = colors.HexColor("#2D2D2D")
LIGHT_GREY = colors.HexColor("#94A3B8")
GREEN      = colors.HexColor("#34D399")
PAGE_BG    = colors.HexColor("#0F1117")

W, H = A4   # 210 × 297 mm


# ── Page template with header / footer ────────────────────────────────────

def _header_footer(canvas, doc):
    canvas.saveState()

    # Full black header bar
    canvas.setFillColor(BLACK)
    canvas.rect(0, H - 28 * mm, W, 28 * mm, fill=1, stroke=0)

    # PENTA — left
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(18 * mm, H - 16 * mm, "PENTA")

    # REAL ESTATE — right of PENTA
    canvas.setFillColor(GOLD)
    canvas.setFont("Helvetica", 9)
    canvas.drawString(44 * mm, H - 15.5 * mm, "REAL ESTATE")

    # Report title — right side
    canvas.setFillColor(LIGHT_GREY)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(W - 18 * mm, H - 16 * mm, "Property Match Report")

    # Gold rule under header
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(0.6)
    canvas.line(18 * mm, H - 29 * mm, W - 18 * mm, H - 29 * mm)

    # Footer
    canvas.setFillColor(LIGHT_GREY)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(18 * mm, 10 * mm,
                      f"Generated by Penta Real Estate Intelligence Platform  ·  {datetime.utcnow().strftime('%d %b %Y, %H:%M')} UTC")
    canvas.drawRightString(W - 18 * mm, 10 * mm, f"Page {doc.page}")

    # Footer rule
    canvas.setStrokeColor(MID_GREY)
    canvas.setLineWidth(0.4)
    canvas.line(18 * mm, 15 * mm, W - 18 * mm, 15 * mm)

    canvas.restoreState()


def _build_doc(buf: io.BytesIO) -> BaseDocTemplate:
    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=35 * mm,
        bottomMargin=22 * mm,
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="main",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=frame, onPage=_header_footer)])
    return doc


# ── Style helpers ──────────────────────────────────────────────────────────

def _styles():
    base = getSampleStyleSheet()
    return {
        "section": ParagraphStyle(
            "section",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=GOLD,
            spaceAfter=4,
            letterSpacing=1.5,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=8,
            textColor=colors.HexColor("#CBD5E1"),
            leading=13,
        ),
        "label": ParagraphStyle(
            "label",
            fontName="Helvetica-Bold",
            fontSize=7,
            textColor=LIGHT_GREY,
        ),
        "value": ParagraphStyle(
            "value",
            fontName="Helvetica",
            fontSize=8,
            textColor=WHITE,
        ),
        "title_main": ParagraphStyle(
            "title_main",
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=WHITE,
            spaceAfter=2,
        ),
        "title_sub": ParagraphStyle(
            "title_sub",
            fontName="Helvetica",
            fontSize=9,
            textColor=LIGHT_GREY,
            spaceAfter=8,
        ),
    }


def _fmt_price(p):
    if not p:
        return "—"
    if p >= 1_000_000:
        return f"AED {p / 1_000_000:.2f}M"
    return f"AED {int(p):,}"


def _score_color(pct: float):
    if pct >= 80:
        return colors.HexColor("#34D399")
    if pct >= 50:
        return colors.HexColor("#F59E0B")
    return colors.HexColor("#F87171")


# ── Requirements summary table ─────────────────────────────────────────────

def _req_table(req: dict) -> Table:
    rows = []

    def add(label, val):
        if val:
            rows.append([label, str(val)])

    add("Budget",       _budget_str(req))
    add("Bedrooms",     req.get("bedrooms"))
    add("Property Type", req.get("property_type"))
    add("Market",       req.get("market_type") or "Both (Secondary + Off-Plan)")
    add("Preferred Areas", ", ".join(req.get("preferred_areas") or []) or None)
    add("Max Handover", str(req.get("max_handover_year")) if req.get("max_handover_year") else None)
    add("Furnishing",   req.get("furnishing"))

    if not rows:
        rows = [["No filters applied", "All listings included"]]

    t = Table(rows, colWidths=[45 * mm, 110 * mm])
    t.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 8),
        ("TEXTCOLOR",   (0, 0), (0, -1), LIGHT_GREY),
        ("TEXTCOLOR",   (1, 0), (1, -1), WHITE),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#1A1D27"), colors.HexColor("#141720")]),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("LINEBELOW",   (0, -1), (-1, -1), 0.4, colors.HexColor("#2D3148")),
    ]))
    return t


def _budget_str(req: dict) -> str | None:
    lo = req.get("budget_min")
    hi = req.get("budget_max")
    if lo and hi:
        return f"{_fmt_price(lo)} — {_fmt_price(hi)}"
    if lo:
        return f"From {_fmt_price(lo)}"
    if hi:
        return f"Up to {_fmt_price(hi)}"
    return None


# ── Results table ──────────────────────────────────────────────────────────

def _results_table(matches: list[dict]) -> Table:
    header = ["#", "Property / Project", "Type", "Price", "Location", "Beds", "Score"]
    rows = [header]

    for i, m in enumerate(matches, 1):
        loc = ", ".join(filter(None, [m.get("community"), m.get("area")])) or "—"
        beds = m.get("bedrooms") or ("—" if m.get("listing_type") == "secondary" else "Various")
        score = m.get("score_pct", 0)

        rows.append([
            str(i),
            (m.get("title") or "")[:55] + ("…" if len(m.get("title") or "") > 55 else ""),
            "Off-Plan" if m.get("listing_type") == "offplan" else "Ready",
            _fmt_price(m.get("price_aed")),
            loc[:38] + ("…" if len(loc) > 38 else ""),
            str(beds),
            f"{score:.0f}%",
        ])

    col_w = [8 * mm, 65 * mm, 18 * mm, 28 * mm, 38 * mm, 12 * mm, 14 * mm]
    t = Table(rows, colWidths=col_w, repeatRows=1)

    style = [
        # Header
        ("BACKGROUND",   (0, 0), (-1, 0), BLACK),
        ("TEXTCOLOR",    (0, 0), (-1, 0), GOLD),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 7.5),
        ("TOPPADDING",   (0, 0), (-1, 0), 7),
        ("BOTTOMPADDING",(0, 0), (-1, 0), 7),
        ("ALIGN",        (0, 0), (-1, 0), "LEFT"),
        # Data rows
        ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",     (0, 1), (-1, -1), 7.5),
        ("TEXTCOLOR",    (0, 1), (-1, -1), colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.HexColor("#1A1D27"), colors.HexColor("#141720")]),
        ("TOPPADDING",   (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 1), (-1, -1), 6),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ALIGN",        (6, 0), (6, -1), "CENTER"),
        ("ALIGN",        (0, 0), (0, -1), "CENTER"),
        ("LINEBELOW",    (0, 0), (-1, 0), 0.5, GOLD),
        ("LINEBELOW",    (0, 1), (-1, -1), 0.3, colors.HexColor("#2D3148")),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]

    # Colour-code score column
    for i, m in enumerate(matches, 1):
        pct = m.get("score_pct", 0)
        style.append(("TEXTCOLOR", (6, i), (6, i), _score_color(pct)))
        style.append(("FONTNAME",  (6, i), (6, i), "Helvetica-Bold"))

    # Bold + white rank column
    for i in range(1, len(matches) + 1):
        style.append(("TEXTCOLOR", (0, i), (0, i), WHITE))
        style.append(("FONTNAME",  (0, i), (0, i), "Helvetica-Bold"))

    t.setStyle(TableStyle(style))
    return t


# ── Main entry point ───────────────────────────────────────────────────────

def generate_match_report(
    matches: list[dict],
    req: dict,
    client_name: str = "",
) -> bytes:
    """
    Build a PDF match report and return it as bytes.

    Parameters
    ----------
    matches   : list of match result dicts (from /match endpoint)
    req       : the original MatchRequest dict
    client_name : optional client name shown on the report
    """
    buf = io.BytesIO()
    doc = _build_doc(buf)
    s = _styles()
    story = []

    # ── Report title ──
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Property Match Report", s["title_main"]))
    sub = datetime.utcnow().strftime("%d %B %Y")
    if client_name:
        sub = f"Prepared for {client_name}  ·  {sub}"
    story.append(Paragraph(sub, s["title_sub"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GOLD, spaceAfter=10))

    # ── Client requirements ──
    story.append(Paragraph("CLIENT REQUIREMENTS", s["section"]))
    story.append(_req_table(req))
    story.append(Spacer(1, 8 * mm))

    # ── Results summary ──
    story.append(Paragraph("MATCHED PROPERTIES", s["section"]))
    story.append(Paragraph(
        f"{len(matches)} propert{'y' if len(matches) == 1 else 'ies'} matched and ranked by compatibility score.",
        s["body"],
    ))
    story.append(Spacer(1, 3 * mm))

    if matches:
        story.append(_results_table(matches))
    else:
        story.append(Paragraph("No matches found for the given requirements.", s["body"]))

    story.append(Spacer(1, 8 * mm))

    # ── Detailed breakdown ──
    story.append(HRFlowable(width="100%", thickness=0.3, color=MID_GREY, spaceAfter=6))
    story.append(Paragraph("DETAILED BREAKDOWN", s["section"]))

    for i, m in enumerate(matches[:10], 1):   # top 10 details
        title = m.get("title") or "Untitled"
        price = _fmt_price(m.get("price_aed"))
        pct   = m.get("score_pct", 0)
        loc   = ", ".join(filter(None, [m.get("community"), m.get("area")])) or "—"
        url   = m.get("listing_url", "")
        ltype = "Off-Plan Project" if m.get("listing_type") == "offplan" else "Ready / Secondary"
        bd    = m.get("breakdown") or {}

        criteria = "  ·  ".join(
            f"{k}: {'✓' if v > 0 else '✗'}" for k, v in bd.items()
        )

        detail_rows = [
            [Paragraph(f"#{i}  {title}", ParagraphStyle(
                "dh", fontName="Helvetica-Bold", fontSize=8.5, textColor=WHITE)),
             Paragraph(f"{pct:.0f}% match", ParagraphStyle(
                "ds", fontName="Helvetica-Bold", fontSize=9,
                textColor=_score_color(pct), alignment=TA_RIGHT))],
            [Paragraph(f"{ltype}  ·  {price}  ·  {loc}", ParagraphStyle(
                "dd", fontName="Helvetica", fontSize=7.5, textColor=LIGHT_GREY)),
             Paragraph(""),
            ],
        ]
        if criteria:
            detail_rows.append([
                Paragraph(criteria, ParagraphStyle(
                    "dc", fontName="Helvetica", fontSize=7, textColor=colors.HexColor("#64748B"))),
                Paragraph(""),
            ])
        if url:
            detail_rows.append([
                Paragraph(f'<link href="{url}">{url[:70]}</link>', ParagraphStyle(
                    "dl", fontName="Helvetica", fontSize=6.5,
                    textColor=colors.HexColor("#60A5FA"))),
                Paragraph(""),
            ])

        dt = Table(detail_rows, colWidths=[doc.width * 0.78, doc.width * 0.22])
        dt.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#1A1D27")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN",         (1, 0), (1, 0), "RIGHT"),
            ("LINEBELOW",     (0, -1), (-1, -1), 0.3, colors.HexColor("#2D3148")),
        ]))
        story.append(dt)
        story.append(Spacer(1, 2 * mm))

    # ── Disclaimer ──
    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=MID_GREY, spaceAfter=4))
    story.append(Paragraph(
        "This report is generated automatically based on live market data scraped from Bayut.com. "
        "Prices and availability are subject to change. Penta Real Estate makes no warranty as to the "
        "accuracy or completeness of this information. This document is confidential and intended solely "
        "for the named recipient.",
        ParagraphStyle("disc", fontName="Helvetica", fontSize=6.5,
                       textColor=colors.HexColor("#475569"), leading=10),
    ))

    doc.build(story)
    return buf.getvalue()
